const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'lOGOUT',
    LOGIN_SUCCESS: 'REGISTER_SUCCESS',
    LOGIN_FAIL: 'REGISTER_FAIL',

    GET_POSTS: 'GET_POSTS',
    GET_LIMIT_POSTS: 'GET_LIMIT_POSTS',
    GET_CATEGORY: 'GET_CATEGORY',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',

};
export default actionTypes;
